general_events = {
    puzzle = {
        [1]={   
            {ev=create_panels}, 
            {ev=ev_create_name_panel},
            {ev=ev_set_tempo, params={"rook",0}},
            {ev=ev_set_tempo, params={"bishop",0}},
            {ev=ev_set_tempo, params={"queen",0}},
            {ev=ev_set_tempo, params={"pawn",0}},
            {ev=ev_set_tempo, params={"king",0}},
            {ev=ev_set_tempo, params={"knight",0}},
            {ev=ev_set_hp, params={"rook",0}},
            {ev=ev_set_hp, params={"bishop",0}},
            {ev=ev_set_hp, params={"queen",0}},
            {ev=ev_set_hp, params={"pawn",0}},
            {ev=ev_set_hp, params={"king",0}},
            {ev=ev_set_hp, params={"knight",0}},
            {ev=ev_disable_shotgun},
            {ev=ev_base_promote, params={"pawn", false}},
            {ev=ev_soul_slot, params={-10, true}},
            {ev=ev_show_name_panel, params="name_1"},
            {ev=mk_square_trigger, params={{event="move_2"},1,1}},
            {ev=mk_square_trigger, params={{event="move_3"},3,1}},
            -- {ev=mk_square_trigger, params={{event="move_4", trigger="4_unlock"},5,1}},
            {ev=mk_square_trigger, params={{event="move_4"},5,1}},
           
            {ev=mk_square_trigger, params={{event="move_5", trigger="5_unlock"},1,3}},
            {ev=mk_square_trigger, params={{event="move_5"},1,3}},
            {ev=mk_square_trigger, params={{event="move_6", trigger="5_solved, 4_solved"},3,3}},
            {ev=mk_square_trigger, params={{event="move_7"},7,2}},
        },
        [2]={
            {ev=ev_soul_slot, params={-1, true}},
            {ev=ev_base_promote, params={"pawn", true}},
            {ev=mk_entity, params={"barrel",1,7}},
            {ev=ev_cond, params={"(1)2"}},
            {ev=ev_spawn, params={3, true, 0,1, nil, {inert=1, iron =1}}},
            {ev=ev_spawn, params={3, true, 2,1, nil, {inert=1, iron =1}}},
            {ev=ev_spawn, params={0, true, 0,2, nil, {iron =1, cd=4}}},
            {ev=ev_spawn, params={0, true, 1,2, nil, {iron =1, cd=4}}},
            {ev=ev_spawn, params={0, true, 2,2, nil, {iron =1, cd=4}}},
            {ev=ev_spawn, params={0, true, 0,0, nil, {iron =1, cd=2}}},
            {ev=ev_spawn, params={0, true, 2,0, nil, {iron =1, cd=2}}},

            {ev=ev_down_dialogue, params="dialogue_puzzle_2_1"},
            {ev=ev_else},
            {ev=ev_spawn, params={3, true, 0,1, nil, {inert=1, iron =1, instant=1}}},
            {ev=ev_spawn, params={3, true, 2,1, nil, {inert=1, iron =1, instant=1}}},
            {ev=ev_spawn, params={0, true, 0,2, nil, {iron =1, cd=4, instant=1}}},
            {ev=ev_spawn, params={0, true, 1,2, nil, {iron =1, cd=4, instant=1}}},
            {ev=ev_spawn, params={0, true, 2,2, nil, {iron =1, cd=4, instant=1}}},
            {ev=ev_spawn, params={0, true, 0,0, nil, {iron =1, cd=2, instant=1}}},
            {ev=ev_spawn, params={0, true, 2,0, nil, {iron =1, cd=2, instant=1}}},
            {ev=ev_end}, 
            {ev=ev_show_tuto_panels, params="2"},
            {ev=ev_show_name_panel, params="name_2"},
            {ev=mk_square_trigger, params={{event="2_solved, 4_unlock, move_1"},1,0}},
        },

        [3]={
            {ev=ev_soul_slot, params={-1, true}},
            {ev=mk_entity, params={"barrel",1,4}},
            {ev=ev_cond, params={"(1)3"}},
            {ev=ev_spawn, params={2, true, 3, 2, nil, {iron=1, cd=1}}},
            {ev=ev_spawn, params={2, true, 5, 2, nil, {iron=1, cd=1}}},
            {ev=ev_spawn, params={2, true, 5, 3, nil, {iron=1, cd=2}}},
            {ev=ev_spawn, params={5, true, 4, 1, nil, {cd=-9999}}},
            {ev=ev_else},
            {ev=ev_spawn, params={2, true, 3, 2, nil, {iron=1, cd=1, instant=1}}},
            {ev=ev_spawn, params={2, true, 5, 2, nil, {iron=1, cd=1, instant=1}}},
            {ev=ev_spawn, params={2, true, 5, 3, nil, {iron=1, cd=2, instant=1}}},
            {ev=ev_spawn, params={5, true, 4, 1, nil, {cd=-9999, instant=1}}},
            {ev=ev_end},
            {ev=ev_show_tuto_panels, params="3"},
            {ev=ev_show_name_panel, params="name_3"},
            {ev=mk_square_trigger, params={{event="3_solved, 5_unlock, move_1", trigger="kingkill"},3,6}},
            
        },

        [4]={
            {ev=ev_cond, params={"(1)4"}},   
            {ev=ev_spawn, params={1, true, 7,5}},
            {ev=ev_spawn, params={3, true, 1,0, nil, {iron = 1, inert =1}}},
            {ev=ev_spawn, params={3, true, 2,0, nil, {iron = 1, inert =1}}},
            {ev=ev_spawn, params={5, true, 0,0, nil, {cd= -9999}}},
            {ev=ev_spawn, params={3, true, 3,0, nil, {iron = 1, inert =1}}},
            {ev=ev_spawn, params={3, true, 4,0, nil, {iron = 1, inert =1}}},
            {ev=ev_spawn, params={3, true, 5,0, nil, {iron = 1, inert =1}}},
            {ev=ev_spawn, params={3, true, 6,0, nil, {iron = 1, inert =1}}},
            {ev=ev_spawn, params={3, true, 7,0, nil, {iron = 1, inert =1}}},

            {ev=ev_spawn, params={9, true, 7,6, nil, {inert=1, knockback = 0}}},
            {ev=ev_spawn, params={9, true, 6,7, nil, {inert=1, knockback = 0}}},
            {ev=ev_else},
            {ev=ev_spawn, params={1, true, 7,5, nil, {instant = 1}}},
            {ev=ev_spawn, params={3, true, 1,0, nil, {iron = 1, inert =1, instant = 1}}},
            {ev=ev_spawn, params={3, true, 2,0, nil, {iron = 1, inert =1, instant = 1}}},
            {ev=ev_spawn, params={5, true, 0,0, nil, {cd= -9999, instant = 1}}},
            {ev=ev_spawn, params={3, true, 3,0, nil, {iron = 1, inert =1, instant = 1}}},
            {ev=ev_spawn, params={3, true, 4,0, nil, {iron = 1, inert =1, instant = 1}}},
            {ev=ev_spawn, params={3, true, 5,0, nil, {iron = 1, inert =1, instant = 1}}},
            {ev=ev_spawn, params={3, true, 6,0, nil, {iron = 1, inert =1, instant = 1}}},
            {ev=ev_spawn, params={3, true, 7,0, nil, {iron = 1, inert =1, instant = 1}}},

            {ev=ev_spawn, params={9, true, 7,6, nil, {inert=1, knockback = 0, instant = 1}}},
            {ev=ev_spawn, params={9, true, 6,7, nil, {inert=1, knockback = 0, instant = 1}}},
            {ev=ev_end},
            {ev=ev_show_tuto_panels, params="4"},
            {ev=ev_show_name_panel, params="name_4"},
        },
        [5]={
            {ev=ev_hop, params= {0, true}},
            {ev=ev_crown, params=true},
            {ev=ev_cond, params={"(1)5"}},   
            {ev=ev_spawn, params={1, true, 7,5}},
            {ev=ev_spawn, params={3, true, 1,6, nil, {iron = 1, cd = -9999}}},
            {ev=ev_spawn, params={3, true, 2,5, nil, {iron = 1, cd = -9999}}},
            {ev=ev_spawn, params={5, true, 0,0, nil, {cd= -9999}}},
            {ev=ev_spawn, params={3, true, 3,4, nil, {iron = 1, cd = -9999}}},
            {ev=ev_spawn, params={3, true, 4,3, nil, {iron = 1, cd = -9999}}},
            {ev=ev_spawn, params={3, true, 5,2, nil, {iron = 1, cd = -9999}}},
            {ev=ev_spawn, params={3, true, 6,1, nil, {iron = 1, cd = -9999}}},
            {ev=ev_spawn, params={3, true, 7,0, nil, {iron = 1, cd = -9999}}},

            {ev=ev_spawn, params={9, true, 7,6, nil, {inert=1, knockback = 0}}},
            {ev=ev_spawn, params={9, true, 6,7, nil, {inert=1, knockback = 0}}},
            {ev=ev_else},
            {ev=ev_spawn, params={1, true, 7,5, nil, {instant =1}}},
            {ev=ev_spawn, params={3, true, 1,6, nil, {iron = 1, cd = -9999,instant =1}}},
            {ev=ev_spawn, params={3, true, 2,5, nil, {iron = 1, cd = -9999,instant =1}}},
            {ev=ev_spawn, params={5, true, 0,0, nil, {cd= -9999,instant =1}}},
            {ev=ev_spawn, params={3, true, 3,4, nil, {iron = 1, cd = -9999,instant =1}}},
            {ev=ev_spawn, params={3, true, 4,3, nil, {iron = 1, cd = -9999,instant =1}}},
            {ev=ev_spawn, params={3, true, 5,2, nil, {iron = 1, cd = -9999,instant =1}}},
            {ev=ev_spawn, params={3, true, 6,1, nil, {iron = 1, cd = -9999,instant =1}}},
            {ev=ev_spawn, params={3, true, 7,0, nil, {iron = 1, cd = -9999,instant =1}}},

            {ev=ev_spawn, params={9, true, 7,6, nil, {inert=1, knockback = 0, instant = 1}}},
            {ev=ev_spawn, params={9, true, 6,7, nil, {inert=1, knockback = 0, instant = 1}}},
            {ev=ev_end},

            {ev=ev_show_tuto_panels, params="5"},
            {ev=ev_show_name_panel, params="name_5"},
        },
        
        [6]={
            {ev=ev_crown, params=true},
            {ev=ev_set_tempo, params={"rook", 8}},
            {ev=mk_square_trigger, params={{event="6_solved, move_1", trigger="kingkill"},3,0}},
            {ev=ev_cond, params={"(1)6"}},
            {ev=ev_spawn, params={0, true, 0,0, nil, {inert=1}}},
            {ev=ev_spawn, params={0, true, 1,0, nil, {inert=1}}},
            {ev=ev_spawn, params={0, true, 2,0, nil, {inert=1}}},
            {ev=ev_spawn, params={0, true, 5,0, nil, {inert=1}}},
            {ev=ev_spawn, params={0, true, 6,0, nil, {inert=1}}},
            {ev=ev_spawn, params={0, true, 7,0, nil, {inert=1}}},
                
            {ev=ev_spawn, params={1, true, 7,5}},
            {ev=ev_spawn, params={3, true, 0,1, nil, {iron = 1, cd = 9}}},
            {ev=ev_spawn, params={3, true, 1,1, nil, {iron = 1, cd = 9}}},
            {ev=ev_spawn, params={5, true, 2,1, nil, {cd= -9999}}},
            {ev=ev_spawn, params={3, true, 3,1, nil, {iron = 1, cd =7}}},
            {ev=ev_spawn, params={3, true, 4,1, nil, {iron = 1, cd =7}}},
            {ev=ev_spawn, params={3, true, 5,1, nil, {iron = 1, cd =5}}},
            {ev=ev_spawn, params={3, true, 6,1, nil, {iron = 1, cd =5}}},
            {ev=ev_spawn, params={3, true, 7,1, nil, {iron = 1, cd =5}}},

            {ev=ev_spawn, params={9, true, 7,6, nil, {inert=1}}},
            {ev=ev_spawn, params={9, true, 6,7, nil, {inert=1}}},
            {ev=ev_else},
            {ev=ev_spawn, params={0, true, 0,0, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={0, true, 1,0, nil, {inert=1 ,instant=1}}},
            {ev=ev_spawn, params={0, true, 2,0, nil, {inert=1,instant=1}}},
            {ev=ev_spawn, params={0, true, 5,0, nil, {inert=1,instant=1}}},
            {ev=ev_spawn, params={0, true, 6,0, nil, {inert=1,instant=1}}},
            {ev=ev_spawn, params={0, true, 7,0, nil, {inert=1,instant=1}}},
                
            {ev=ev_spawn, params={1, true, 7,5}},
            {ev=ev_spawn, params={3, true, 0,1, nil, {iron = 1, cd = 9,instant=1}}},
            {ev=ev_spawn, params={3, true, 1,1, nil, {iron = 1, cd = 9,instant=1}}},
            {ev=ev_spawn, params={5, true, 2,1, nil, {cd= -9999,instant=1}}},
            {ev=ev_spawn, params={3, true, 3,1, nil, {iron = 1, cd =7,instant=1}}},
            {ev=ev_spawn, params={3, true, 4,1, nil, {iron = 1, cd =7,instant=1}}},
            {ev=ev_spawn, params={3, true, 5,1, nil, {iron = 1, cd =5,instant=1}}},
            {ev=ev_spawn, params={3, true, 6,1, nil, {iron = 1, cd =5,instant=1}}},
            {ev=ev_spawn, params={3, true, 7,1, nil, {iron = 1, cd =5,instant=1}}},

            {ev=ev_spawn, params={9, true, 7,6, nil, {inert=1}}},
            {ev=ev_spawn, params={9, true, 6,7, nil, {inert=1}}},
            {ev=ev_cond, params={"(2)6, not_6_solved"}},
            {ev=ev_down_dialogue, params="dialogue_puzzle_6_2"},
            {ev=ev_end},
            {ev=ev_end},
            {ev=ev_show_tuto_panels, params="6_1"},
            {ev=ev_show_name_panel, params="name_6"},
        },
        [7]={
            {ev=ev_set_tempo, params={"rook",0}},
            {ev=ev_set_tempo, params={"bishop",0}},
            {ev=ev_set_tempo, params={"queen",0}},
            {ev=ev_set_tempo, params={"pawn",0}},
            {ev=ev_set_tempo, params={"king",0}},
            {ev=ev_set_tempo, params={"knight",0}},
            {ev=ev_set_hp, params={"rook",0}},
            {ev=ev_set_hp, params={"bishop",0}},
            {ev=ev_set_hp, params={"queen",0}},
            {ev=ev_set_hp, params={"pawn",0}},
            {ev=ev_set_hp, params={"king",0}},
            {ev=ev_set_hp, params={"knight",0}},
            {ev=ev_disable_shotgun},
            {ev=ev_base_promote, params={"pawn", false}},
            {ev=ev_soul_slot, params={-10, true}},
            {ev=ev_show_name_panel, params="name_7"},
        
            {ev=mk_square_trigger, params={{event="move_1"},0,2}},
            {ev=mk_square_trigger, params={{event="move_8"},1,1}},
            {ev=mk_square_trigger, params={{event="move_9"},3,1}},
        },

        [8]={
            {ev=ev_offset_soul_slot},
            {ev=ev_souls, params={1, true}},
            {ev=ev_cond, params={"(1)8"}},
            {ev=ev_spawn, params={1, true, 0, 0, nil, {inert=1}}},
            {ev=ev_spawn, params={1, true, 1, 0, nil, {inert=1}}},
            {ev=ev_spawn, params={1, true, 3, 0, nil, {inert=1}}},
            {ev=ev_spawn, params={0, true, 4, 0, nil, {inert=1}}},
            {ev=ev_spawn, params={3, true, 6, 0, nil, {inert=1}}},
            {ev=ev_spawn, params={1, true, 7, 0, nil, {inert=1}}},
            {ev=ev_spawn, params={0, true, 9, 0, nil, {inert=1}}},
            {ev=ev_spawn, params={0, true, 7, 1, nil, {inert=1}}},
            {ev=ev_spawn, params={3, true, 6, 2, nil, {inert=1}}},
            {ev=ev_spawn, params={0, true, 7, 2, nil, {inert=1}}},
            {ev=ev_spawn, params={0, true, 5, 3, nil, {inert=1}}},
            {ev=ev_spawn, params={0, true, 9, 3, nil, {inert=1}}},
            {ev=ev_spawn, params={3, true, 6, 4, nil, {inert=1}}},
            {ev=ev_spawn, params={0, true, 7, 4, nil, {inert=1}}},
            {ev=ev_spawn, params={1, true, 3, 5, nil, {inert=1}}},
            {ev=ev_spawn, params={1, true, 5, 5, nil, {inert=1}}},
            {ev=ev_spawn, params={1, true, 0, 6, nil, {inert=1}}},
            {ev=ev_spawn, params={3, true, 6, 6, nil, {inert=1}}},
            {ev=ev_spawn, params={0, true, 7, 6, nil, {inert=1}}},
            {ev=ev_spawn, params={1, true, 9, 6, nil, {inert=1}}},
            {ev=ev_spawn, params={0, true, 7, 7, nil, {inert=1}}},
            {ev=ev_spawn, params={3, true, 0, 8, nil, {inert=1}}},
            {ev=ev_spawn, params={2, true, 5, 8, nil, {inert=1}}},
            {ev=ev_spawn, params={3, true, 0, 9, nil, {inert=1}}},
            {ev=ev_spawn, params={2, true, 5, 9, nil, {inert=1}}},
            {ev=ev_spawn, params={3, true, 9, 9, nil, {inert=1}}},
            {ev=ev_else},					
            {ev=ev_spawn, params={1, true, 0, 0, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={1, true, 1, 0, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={1, true, 3, 0, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={0, true, 4, 0, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={3, true, 6, 0, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={1, true, 7, 0, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={0, true, 9, 0, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={0, true, 7, 1, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={3, true, 6, 2, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={0, true, 7, 2, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={0, true, 5, 3, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={0, true, 9, 3, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={3, true, 6, 4, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={0, true, 7, 4, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={1, true, 3, 5, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={1, true, 5, 5, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={1, true, 0, 6, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={3, true, 6, 6, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={0, true, 7, 6, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={1, true, 9, 6, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={0, true, 7, 7, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={3, true, 0, 8, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={2, true, 5, 8, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={3, true, 0, 9, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={2, true, 5, 9, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={3, true, 9, 9, nil, {inert=1, instant=1}}},
            {ev=ev_end},
            {ev=ev_show_tuto_panels, params="8"},
            {ev=ev_show_name_panel, params="name_8"},
            {ev=mk_square_trigger, params={{event="8_solved, move_7"},8,0}},
        },
        [9]={
            {ev=ev_offset_soul_slot},
            {ev=ev_soul_slot, params={1, true}},
            {ev=ev_souls, params={1, true}},
            {ev=ev_souls, params={3, true}},
            {ev=ev_cond, params={"(1)9"}},
            {ev=ev_spawn, params={0, true, 2, 0, nil, {inert=1}}},
            {ev=ev_spawn, params={3, true, 9, 1, nil, {inert=1}}},
            {ev=ev_spawn, params={5, true, 2, 2, nil, {inert=1}}},
            {ev=ev_spawn, params={0, true, 5, 2, nil, {inert=1}}},
            {ev=ev_spawn, params={3, true, 7, 2, nil, {inert=1}}},
            {ev=ev_spawn, params={0, true, 6, 3, nil, {inert=1}}},
            {ev=ev_spawn, params={0, true, 9, 3, nil, {inert=1}}},
            {ev=ev_spawn, params={1, true, 4, 4, nil, {inert=1}}},
            {ev=ev_spawn, params={5, true, 6, 4, nil, {inert=1}}},
            {ev=ev_spawn, params={1, true, 1, 5, nil, {inert=1}}},
            {ev=ev_spawn, params={2, true, 9, 5, nil, {inert=1}}},
            {ev=ev_spawn, params={1, true, 1, 6, nil, {inert=1}}},
            {ev=ev_spawn, params={0, true, 2, 7, nil, {inert=1}}},
            {ev=ev_spawn, params={3, true, 9, 8, nil, {inert=1}}},
            {ev=ev_spawn, params={1, true, 2, 9, nil, {inert=1}}},
            {ev=ev_spawn, params={3, true, 3, 9, nil, {inert=1}}},
            {ev=ev_else},
            {ev=ev_spawn, params={0, true, 2, 0, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={3, true, 9, 1, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={5, true, 2, 2, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={0, true, 5, 2, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={3, true, 7, 2, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={0, true, 6, 3, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={0, true, 9, 3, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={1, true, 4, 4, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={5, true, 6, 4, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={1, true, 1, 5, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={2, true, 9, 5, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={1, true, 1, 6, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={0, true, 2, 7, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={3, true, 9, 8, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={1, true, 2, 9, nil, {inert=1, instant=1}}},
            {ev=ev_spawn, params={3, true, 3, 9, nil, {inert=1, instant=1}}},
            {ev=ev_end},
            {ev=ev_show_tuto_panels, params="9"},
            {ev=ev_show_name_panel, params="name_9"},
            {ev=mk_square_trigger, params={{event="9_solved, move_7"},0,9}},
        
        }
    }
}